### DISCUSSION TITLE
Using rich with dictConfig for file logging

### DISCUSSION THREAD

**Discussion by astrochun** [Textualize/rich#2189] [Q&A]
I have a FastAPI application where I previously configured stdout and file logging using the python `logging` standard library.  Here, I'm using YAML for configuration for both the application and `uvicorn` log. I'm now working on migrating this to use Rich.

I'm able to configure the console logs to use Rich. The YAML config looks something like this:
```yaml
version: 1
disable_existing_loggers: false
formatters:
  precise:
    datefmt: "[%x %X]"
    (): 'uvicorn.logging.DefaultFormatter'
    fmt: '%(asctime)s %(name)-14s - %(levelprefix)s [%(module)s.%(funcName)s] %(message)s'
handlers:
  console:
    level: INFO
    class: rich.logging.RichHandler
    log_time_format: "[%x %X]"
    markup: True
    show_path: True
  file:
    level: DEBUG
    formatter: precise
    class: logging.handlers.TimedRotatingFileHandler
    when: 'W0'
    backupCount: 4
    filename: app.log
loggers:
  my-app:
    level: DEBUG
    handlers: [console, file]
    propagate: no
```

However, I wonder if there's a way to pass a `Rich` Formatter with `TimedRotatingFileHandler` as I do like rich text and would like for my `log.*()` to appear as it would be in the log (albeit rich color would not be available but at least emoji will be handled).

I know there's a way to specify a `Console` with `file=open(...)`, but don't think rotating file is supported within `Rich`. Thus, I think replacing the formatter used in `precise` may be the best solution. Has anyone done this or know how?
