### DISCUSSION TITLE
Welcome to rich Discussions!

### DISCUSSION THREAD

**Discussion by willmcgugan** [Textualize/rich#322] [General]
## 👋 Welcome!

  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by oleksis** [comment]
Hi, I'm Oleksis, a Computer Engineer 👨🏾‍💻. I have collaborated with Rich in the translation of the documentation. It would be a good idea this month to kickstart the project through Hacktoberfest and create / tag some PRs to encourage others to collaborate with the project. 

Greetings and Happy coding!

**Reply by willmcgugan** [reply]
👋

**Reply by Adilius** [reply]
What language have you translated the documentation to? And where is it translated?

**Reply by oleksis** [reply]
I started/updated the [Spanish docs](https://github.com/willmcgugan/rich/commit/2695ab90e4d679e5c54c44646dca98f79988ace1) . You can check the [README.es.md](https://github.com/willmcgugan/rich/blob/master/README.es.md)

**Reply by Adilius** [reply]
I see, thanks. I'm wondering if translation of the readme to swedish is needed/wanted then I could do that. Just looking to contribute :)

**Reply by willmcgugan** [reply]
@Adilius A Swedish translation would be much appreciated!

**Reply by Adilius** [reply]
Created!

**Reply by Adilius** [reply]
I don't want to clog up the commits log, but still want to keep the swedish translation as updated as possible. 
Any guidelines on how often to update to match the english README?
Currently have an github file watcher email service active on the english README

**Reply by oleksis** [reply]
@Adilius We can make Github Action on the README.en.md file change and send a comment on this discussions with the mentioning the interested parties

**Reply by willmcgugan** [reply]
@Adilius Feel free to update as frequently as you like.

**Reply by oleksis** [reply]
@willmcgugan  Can test this 💡 (Need by tested)

```yml
name: README.md Changed

on: 
  push:
    paths:
      - 'README.md'

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to README Authors
      run: |
        gh api graphql -H 'GraphQL-Features: discussions_api' -f body='@willmcgugan @oleksis @Adilius README.md changed' -F discussionId='MDEwOkRpc2N1c3Npb24yMjU2MA==' -F replyToId='MDE3OkRpc2N1c3Npb25Db21tZW50ODk1OTg=' -f query='
        mutation($body: String!, $discussionId: ID!, $replyToId: ID!){
            addDiscussionComment(input:{body: $body , discussionId: $discussionId, replyToId: $replyToId }){
                comment{
                    id
                }
            }
        }'

```
